-- Populate regulatory_controls with pre-defined controls
INSERT INTO public.regulatory_controls (id, domain, jurisdiction, source_regulation, description, frequency, specific_deadline, responsible_person, required_evidence, next_due_date, status, maturity_level, maturity_justification, notes)
VALUES
-- D1: Licenciamiento y gobierno corporativo
('D1-F01', 'D1 — Licenciamiento y gobierno corporativo', 'FSCA', 'FAIS Act S.8', 'Mantener licencia FSP activa y vigente', 'Anual', 'Anual (renovación)', 'Mauro Serrano', 'Certificado de licencia FSP vigente', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', 'Licencia FSP principal'),
('D1-F02', 'D1 — Licenciamiento y gobierno corporativo', 'FSCA', 'FSCA Levy Rules', 'Pago del levy anual FSCA', 'Anual', 'Anual', 'Mauro Serrano', 'Comprobante de pago', CURRENT_DATE + INTERVAL '3 months', 'En progreso', 1, 'Initial state — pending first assessment', 'Pago de tasa reguladora anual'),
('D1-F03', 'D1 — Licenciamiento y gobierno corporativo', 'FSCA', 'FAIS Act S.14', 'Notificar a FSCA cualquier cambio material (directores, actividades, estructura accionaria)', 'Por evento', 'Por evento', 'Mauro Serrano', 'Notificación enviada + acuse de recibo FSCA', NULL, 'Compliant', 1, 'Initial state — pending first assessment', 'Cambios societarios u operativos'),
('D1-F04', 'D1 — Licenciamiento y gobierno corporativo', 'FSCA', 'FAIS Act S.2', 'Nombrar Key Individual (KI) para cada categoría de producto', 'Por evento', 'Por evento / continua', 'Mauro Serrano', 'Registro de KIs aprobados por FSCA', NULL, 'Compliant', 1, 'Initial state — pending first assessment', 'Designaciones de responsables clave'),
('D1-F05', 'D1 — Licenciamiento y gobierno corporativo', 'FSCA', 'FAIS Act S.17', 'Nombrar Compliance Officer si hay más de 1 KI o representantes', 'Por evento', 'Por evento', 'Mauro Serrano', 'Designación formal + registro FSCA', NULL, 'Compliant', 1, 'Initial state — pending first assessment', 'Estructura de oficiales de compliance'),

('D1-M01', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'Securities Act 2005 S.15', 'Renovar Investment Dealer Licence anualmente', 'Anual', 'Anual (aniversario de la licencia)', 'Mauro Serrano', 'Certificado de licencia FSC vigente', CURRENT_DATE + INTERVAL '8 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D1-M02', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'FSC Consolidated Licensing & Fees Rules 2008', 'Pagar Annual Licence Fee (MUR 600,000–1,000,000 Investment Dealer)', 'Anual', 'Anual (aniversario)', 'Mauro Serrano', 'Comprobante de pago FSC', CURRENT_DATE + INTERVAL '8 months', 'En progreso', 1, 'Initial state — pending first assessment', 'Tarifa de licencia anual Mauritius'),
('D1-M03', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'FSC Circular / Financial Services Act S.71', 'Mantener mínimo 2 directores residentes en Mauritius con criterio independiente', 'Continua', 'Continua', 'Mauro Serrano', 'CVs de directores + prueba de residencia', NULL, 'Compliant', 1, 'Initial state — pending first assessment', 'Requisito de sustancia local'),
('D1-M04', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'FSC Substance Requirements', 'Mantener cuenta bancaria principal en Mauritius', 'Continua', 'Continua', 'Mauro Serrano', 'Estado de cuenta bancaria activa en Mauritius', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D1-M05', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'Financial Services Act S.71', 'Mantener registros contables en la sede registrada en Mauritius', 'Continua', 'Continua', 'Mauro Serrano', 'Contrato con Management Company o evidencia de registros locales', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D1-M06', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'Financial Services Act S.77', 'Contratar Management Company licenciada por FSC', 'Continua', 'Continua', 'Mauro Serrano', 'Contrato vigente con Management Company', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D1-M07', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'Securities Act 2005', 'Notificar FSC ante cambios materiales (directores, accionistas, actividades, LPs)', 'Por evento', 'Por evento', 'Mauro Serrano', 'Notificación enviada + acuse FSC', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D1-M08', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'FSC GBC Substance Requirements', 'Presentar Annual Substance Filing (descripción de actividades, empleados, gastos en Mauritius)', 'Anual', 'Anual', 'Mauro Serrano', 'Formulario de substance filing completado y radicado', CURRENT_DATE + INTERVAL '9 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D1-M09', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'Securities (Licensing) Rules 2007 Rule 14', 'Mantener capital mínimo estatutario (MUR 1,000,000 para Investment Dealer excl. underwriting)', 'Continua', 'Continua', 'Mauro Serrano', 'Balance sheet que evidencia capital', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D1-M10', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'Securities Act 2005 / FSC Licensing Criteria', 'Nombrar Compliance Officer', 'Por evento', 'Por evento', 'Mauro Serrano', 'Designación formal + CDD del Compliance Officer', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D1-M11', 'D1 — Licenciamiento y gobierno corporativo', 'FSC Mauritius', 'FIAMLA 2002 / FSC AML Handbook', 'Nombrar MLRO y Deputy MLRO', 'Por evento', 'Por evento', 'Mauro Serrano', 'Designación formal + CDD del MLRO', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),

-- D2: Solidez financiera y capital
('D2-F01', 'D2 — Solidez financiera y capital', 'FSCA', 'Board Notice 194/2017 Cap.6', 'Activos > Pasivos en todo momento (solvencia general)', 'Continua', 'Continua', 'Mauro Serrano', 'Balance sheet mensual interno', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-F02', 'D2 — Solidez financiera y capital', 'FSCA', 'BN 194 Cap.6', 'Activos corrientes > Pasivos corrientes (capital de trabajo)', 'Continua', 'Continua', 'Mauro Serrano', 'Balance sheet mensual interno', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-F03', 'D2 — Solidez financiera y capital', 'FSCA', 'BN 194 Cap.6', 'Activos líquidos >= 4/52 semanas del gasto anual ajustado (~1 mes de opex)', 'Continua', 'Continua', 'Mauro Serrano', 'Cálculo mensual documentado', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-F04', 'D2 — Solidez financiera y capital', 'FSCA', 'BN 194', 'Presentar Form A (Liquidity Calculation) — Cat. I: anual; Cat. II: semestral dentro de 45 días', 'Semestral', 'Semestral dentro de 45 días del cierre', 'Mauro Serrano', 'Form A radicado ante FSCA con acuse', CURRENT_DATE + INTERVAL '45 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D2-F05', 'D2 — Solidez financiera y capital', 'FSCA', 'BN 194 Cap.6', 'Early Warning: notificar FSCA inmediatamente si activos exceden pasivos por < 10%', 'Por evento', 'Por evento', 'Mauro Serrano', 'Notificación enviada + timestamp', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-F06', 'D2 — Solidez financiera y capital', 'FSCA', 'FAIS Act S.18', 'Mantener seguro PI/FG mínimo ZAR 1M o ZAR 5M', 'Anual', 'Anual (renovación póliza)', 'Mauro Serrano', 'Póliza de seguro vigente', CURRENT_DATE + INTERVAL '11 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),

('D2-M01', 'D2 — Solidez financiera y capital', 'FSC Mauritius', 'Securities (Licensing) Rules 2007 Rule 14', 'Mantener capital mínimo no deteriorado >= MUR 1,000,000 en todo momento', 'Continua', 'Continua', 'Mauro Serrano', 'Balance sheet con capital', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-M02', 'D2 — Solidez financiera y capital', 'FSC Mauritius', 'SEM Financial Reporting Rules 2010', 'Mantener capital adecuado >= 9 meses de gastos fijos (FEBR)', 'Continua', 'Continua', 'Mauro Serrano', 'Cálculo FEBR documentado', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-M03', 'D2 — Solidez financiera y capital', 'FSC Mauritius', 'SEM Financial Reporting Rules 2010', 'Presentar Capital Adequacy Return trimestral ante SEM', 'Trimestral', 'Dentro de los 10 días hábiles del cierre del trimestre', 'Mauro Serrano', 'Capital Adequacy Return radicado', CURRENT_DATE + INTERVAL '10 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D2-M04', 'D2 — Solidez financiera y capital', 'FSC Mauritius', 'SEM Financial Reporting Rules 2010 Rule 14.3', 'Notificar inmediatamente al SEM si hay riesgo de incumplimiento de capital', 'Por evento', 'Por evento', 'Mauro Serrano', 'Notificación formal enviada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D2-M05', 'D2 — Solidez financiera y capital', 'FSC Mauritius', 'SEM Financial Reporting Rules 2010', 'Mantener registros contables actualizados en todo momento', 'Continua', 'Continua', 'Mauro Serrano', 'Libros contables actualizados', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),

-- D3: KYC / AML / CFT
('D3-F01', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA', 'Implementar programa AML/CFT escrito (políticas, procedimientos, controles)', 'Anual', 'Anual (revisión)', 'Mauro Serrano', 'Manual AML/CFT actualizado y aprobado', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D3-F02', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA S.21', 'Realizar Customer Due Diligence (CDD) completo en el onboarding de cada cliente', 'Por evento', 'Por cliente', 'Mauro Serrano', 'Expediente de cliente con documentación CDD', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-F03', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA S.21B', 'Realizar Enhanced Due Diligence (EDD) para PEPs y clientes de alto riesgo', 'Por evento', 'Por cliente de alto riesgo', 'Mauro Serrano', 'Expediente EDD con aprobación del KI', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-F04', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA S.22', 'Monitoreo continuo de transacciones de clientes (transaction monitoring)', 'Continua', 'Continua', 'Mauro Serrano', 'Logs de monitoreo + alertas documentadas', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-F05', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA S.29', 'Reportar Suspicious Transaction Reports (STRs) al FIC', 'Por evento', 'Por evento', 'Mauro Serrano', 'Copia de STR radicado ante FIC', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-F06', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA S.23', 'Conservar registros de clientes y transacciones por mínimo 5 años', 'Continua', 'Continua', 'Mauro Serrano', 'Política de retención de registros implementada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-F07', 'D3 — KYC / AML / CFT', 'FSCA', 'FICA', 'Capacitación AML anual obligatoria para todo el personal', 'Anual', 'Anual', 'Mauro Serrano', 'Registros de asistencia + material de capacitación', CURRENT_DATE + INTERVAL '5 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),

('D3-M01', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAMLA 2002 / FSC AML Handbook', 'Implementar programa AML/CFT escrito conforme a FSC AML/CFT Handbook', 'Anual', 'Anual (revisión)', 'Mauro Serrano', 'Manual AML/CFT actualizado, firmado por MLRO', CURRENT_DATE + INTERVAL '7 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D3-M02', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAMLA / CRS', 'Realizar CDD completo en onboarding de todos los clientes (incluyendo TIN para CRS)', 'Por evento', 'Por cliente', 'Mauro Serrano', 'Expediente de cliente con documentación CDD + TIN', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-M03', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAML Regulations 2018', 'Identificar y aplicar EDD a PEPs, clientes de alto riesgo', 'Por evento', 'Por cliente de alto riesgo', 'Mauro Serrano', 'Expediente EDD aprobado por MLRO', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-M04', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAMLA / FIAML Regulations', 'Screening de clientes contra listas de sanciones', 'Continua', 'Continua', 'Mauro Serrano', 'Logs de screening con fecha y resultado', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-M05', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAMLA S.17', 'Monitoreo continuo de transacciones', 'Continua', 'Continua', 'Mauro Serrano', 'Logs de monitoreo + alertas documentadas', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-M06', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAMLA S.14', 'Reportar STRs al Financial Intelligence Unit (FIU) de Mauritius', 'Por evento', 'Por evento', 'Mauro Serrano', 'Copia de STR radicado + acuse FIU', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-M07', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FIAMLA S.20', 'Conservar registros de clientes y transacciones por mínimo 7 años', 'Continua', 'Continua', 'Mauro Serrano', 'Política de retención de registros implementada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D3-M08', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FSC AML Handbook', 'Presentar AML/CFT Annual Report al FSC', 'Anual', 'Anual', 'Mauro Serrano', 'Reporte AML/CFT anual radicado', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D3-M09', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FSC AML Handbook', 'Capacitación AML anual para todo el personal', 'Anual', 'Anual', 'Mauro Serrano', 'Registros de asistencia + material', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D3-M10', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'FSC AML Handbook', 'Realizar auditoría AML independiente anual', 'Anual', 'Anual', 'Mauro Serrano', 'Informe de auditoría AML', CURRENT_DATE + INTERVAL '11 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D3-M11', 'D3 — KYC / AML / CFT', 'FSC Mauritius', 'Common Reporting Standard / OECD', 'Presentar CRS Annual Return a la Mauritius Revenue Authority (MRA)', 'Anual', 'Anual', 'Mauro Serrano', 'CRS Return radicado ante MRA', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),

-- D4: Protección al cliente
('D4-F01', 'D4 — Protección al cliente', 'FSCA', 'FAIS General Code of Conduct S.3', 'Segregar fondos de clientes en cuenta bancaria separada', 'Continua', 'Continua', 'Mauro Serrano', 'Estado de cuenta bancaria segregada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D4-F02', 'D4 — Protección al cliente', 'FSCA', 'FAIS General Code', 'Realizar reconciliación de cuentas de clientes (mensual mínimo)', 'Mensual', 'Mensual', 'Mauro Serrano', 'Reportes de reconciliación firmados', CURRENT_DATE + INTERVAL '1 month', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D4-F03', 'D4 — Protección al cliente', 'FSCA', 'FAIS General Code / ODP Conduct Standard 2018', 'Garantizar best execution en órdenes de clientes', 'Continua', 'Continua', 'Mauro Serrano', 'Política de Best Execution documentada + logs', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D4-F04', 'D4 — Protección al cliente', 'FSCA', 'FAIS General Code S.7', 'Divulgar riesgos a clientes antes de operar (Risk Disclosure)', 'Por evento', 'Por cliente (onboarding)', 'Mauro Serrano', 'Formulario de Risk Disclosure firmado por cliente', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D4-F05', 'D4 — Protección al cliente', 'FSCA', 'FAIS General Code S.3', 'Implementar política y procedimiento de gestión de quejas de clientes', 'Anual', 'Por evento / revisión anual', 'Mauro Serrano', 'Registro de quejas + tiempos de respuesta', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D4-F06', 'D4 — Protección al cliente', 'FSCA', 'FAIS General Code', 'Proveer estados de cuenta periódicos a clientes', 'Mensual', 'Mensual/Trimestral', 'Mauro Serrano', 'Evidencia de envío de estados de cuenta', CURRENT_DATE + INTERVAL '1 month', 'En progreso', 1, 'Initial state — pending first assessment', ''),

('D4-M01', 'D4 — Protección al cliente', 'FSC Mauritius', 'FSC Safeguarding of Client Assets Rules', 'Segregar fondos de clientes en cuenta(s) bancaria(s) separadas', 'Continua', 'Continua', 'Mauro Serrano', 'Estado de cuenta bancaria segregada en Mauritius', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D4-M02', 'D4 — Protección al cliente', 'FSC Mauritius', 'FSC Client Money Rules', 'Realizar reconciliación de cuentas de clientes (mensual)', 'Mensual', 'Mensual', 'Mauro Serrano', 'Reportes de reconciliación firmados', CURRENT_DATE + INTERVAL '1 month', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D4-M03', 'D4 — Protección al cliente', 'FSC Mauritius', 'Securities Act 2005 S.56', 'Garantizar best execution', 'Continua', 'Continua', 'Mauro Serrano', 'Política de Best Execution documentada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D4-M04', 'D4 — Protección al cliente', 'FSC Mauritius', 'FSC Licensing Conditions', 'Divulgar riesgos a clientes (Risk Disclosure)', 'Por evento', 'Por cliente (onboarding)', 'Mauro Serrano', 'Formulario de Risk Disclosure firmado', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D4-M05', 'D4 — Protección al cliente', 'FSC Mauritius', 'FSC Conduct Requirements', 'Implementar política de gestión de quejas', 'Anual', 'Por evento / revisión anual', 'Mauro Serrano', 'Registro de quejas + resoluciones', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),

-- D5: Formación y competencia del equipo
('D5-F01', 'D5 — Formación y competencia del equipo', 'FSCA', 'Board Notice 194/2017 Cap.2', 'Key Individual aprueba Examen Regulatorio RE1', 'Única', 'Única (por KI)', 'Mauro Serrano', 'Certificado RE1 por KI', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D5-F02', 'D5 — Formación y competencia del equipo', 'FSCA', 'BN 194 Cap.2', 'Representantes aprueban Examen Regulatorio RE5', 'Única', 'Única (por representante)', 'Mauro Serrano', 'Certificado RE5 por representante', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D5-F03', 'D5 — Formación y competencia del equipo', 'FSCA', 'BN 194 Cap.2', 'Todos los KIs y representantes obtienen calificación reconocida FSCA', 'Única', 'Única (por persona)', 'Mauro Serrano', 'Certificado de calificación reconocida', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D5-F04', 'D5 — Formación y competencia del equipo', 'FSCA', 'BN 194 Cap.2', 'Completar Product Specific Training (PST) antes de prestar servicios', 'Por evento', 'Por producto/persona', 'Mauro Serrano', 'Certificado PST por producto y persona', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D5-F05', 'D5 — Formación y competencia del equipo', 'FSCA', 'BN 194 Cap.2', 'Completar CPD mínimo 18 horas anuales — límite 31 de mayo', 'Anual', 'Anual (límite 31 de mayo)', 'Mauro Serrano', 'Registros de CPD por persona', CURRENT_DATE + INTERVAL '11 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D5-F06', 'D5 — Formación y competencia del equipo', 'FSCA', 'BN 194', 'Documentar historial de capacitación de cada KI y representante', 'Continua', 'Continua', 'Mauro Serrano', 'Expedientes individuales de capacitación actualizados', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),

('D5-M01', 'D5 — Formación y competencia del equipo', 'FSC Mauritius', 'Securities Act 2005 / FSC Licensing Criteria', 'Verificar fit & proper de todos los directores, Compliance Officer y MLRO', 'Anual', 'Por evento (nombramiento) + revisión anual', 'Mauro Serrano', 'Personal Questionnaire Form + CDD completo', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D5-M02', 'D5 — Formación y competencia del equipo', 'FSC Mauritius', 'FIAMLA / FSC AML Handbook', 'Capacitación AML anual para todos los empleados', 'Anual', 'Anual', 'Mauro Serrano', 'Registros de asistencia firmados', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),

-- D6: Reportes periódicos a reguladores
('D6-F01', 'D6 — Reportes periódicos a reguladores', 'FSCA', 'FAIS Act S.19', 'Presentar estados financieros anuales auditados ante FSCA', 'Anual', 'Dentro de 4 meses del cierre del ejercicio', 'Mauro Serrano', 'Estados financieros radicados + acuse FSCA', CURRENT_DATE + INTERVAL '4 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-F02', 'D6 — Reportes periódicos a reguladores', 'FSCA', 'BN 194', 'Presentar Form A (Liquidity Calculation)', 'Semestral', 'Semestral dentro de 45 días del cierre', 'Mauro Serrano', 'Form A radicado + acuse', CURRENT_DATE + INTERVAL '45 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-F03', 'D6 — Reportes periódicos a reguladores', 'FSCA', 'BN 194 Cap.6', 'Notificar Early Warning al FSCA', 'Por evento', 'Inmediatamente', 'Mauro Serrano', 'Notificación enviada + timestamp', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D6-F04', 'D6 — Reportes periódicos a reguladores', 'FSCA', 'FAIS Act S.14', 'Notificar FSCA ante cambios materiales', 'Por evento', 'Antes de implementar el cambio', 'Mauro Serrano', 'Notificación con acuse', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),

('D6-M01', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'Securities Act 2005 S.20', 'Presentar estados financieros anuales auditados ante FSC', 'Anual', 'Dentro de 6 meses del cierre del ejercicio', 'Mauro Serrano', 'Reporte anual radicado ante FSC', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M02', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'SEM Financial Reporting Rules 2010', 'Presentar Capital Adequacy Return trimestral ante SEM', 'Trimestral', 'Dentro de 10 días hábiles del cierre del trimestre', 'Mauro Serrano', 'Capital Adequacy Return radicado', CURRENT_DATE + INTERVAL '10 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M03', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'FSC Licensing Conditions', 'Presentar Quarterly Financial Return ante FSC', 'Trimestral', 'Dentro de 1 mes del cierre del trimestre', 'Mauro Serrano', 'Reporte trimestral radicado', CURRENT_DATE + INTERVAL '30 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M04', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'Companies Act 2001', 'Presentar Annual Return ante Companies Division (Registrar)', 'Anual', 'Aniversario de incorporación', 'Mauro Serrano', 'Annual Return radicado', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M05', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'FSC Consolidated Licensing & Fees Rules', 'Pagar Annual Licence Fee FSC', 'Anual', 'Aniversario de la licencia', 'Mauro Serrano', 'Comprobante de pago', CURRENT_DATE + INTERVAL '8 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M06', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'FSC AML Handbook', 'Presentar AML/CFT Annual Report', 'Anual', 'Según indicación FSC', 'Mauro Serrano', 'Reporte AML radicado', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M07', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'CRS / OECD', 'Presentar CRS Annual Return ante MRA', 'Anual', 'Según calendario MRA', 'Mauro Serrano', 'CRS Return radicado', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D6-M08', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'Securities Act 2005', 'Notificar FSC ante cambios materiales', 'Por evento', 'Inmediatamente', 'Mauro Serrano', 'Notificación con acuse FSC', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D6-M09', 'D6 — Reportes periódicos a reguladores', 'FSC Mauritius', 'FSC GBC Substance Requirements', 'Presentar Annual Substance Filing', 'Anual', 'Con el reporte anual', 'Mauro Serrano', 'Substance filing completado', CURRENT_DATE + INTERVAL '6 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),

-- D7: Tecnología, datos y ciberseguridad
('D7-01', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'FAIS / FSC / ISO 27001', 'Implementar política de seguridad de la información', 'Anual', 'Anual (revisión)', 'Mauro Serrano', 'Política aprobada y vigente', CURRENT_DATE + INTERVAL '9 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D7-02', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'FAIS / FSC / ISO 27001 A.9', 'Controlar acceso a sistemas críticos (principio de mínimo privilegio)', 'Continua', 'Continua', 'Mauro Serrano', 'Matriz de accesos documentada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D7-03', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'FAIS / FSC', 'Implementar backup y plan de recuperación ante desastres', 'Anual', 'Anual (prueba)', 'Mauro Serrano', 'Evidencia de prueba de recuperación', CURRENT_DATE + INTERVAL '10 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D7-04', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'ISO 27001 A.12', 'Gestionar vulnerabilidades y parches de sistemas', 'Continua', 'Continua / Trimestral', 'Mauro Serrano', 'Log de gestión de parches', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D7-05', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'POPIA / Data Protection Act 2017', 'Proteger datos personales de clientes (privacidad)', 'Continua', 'Continua', 'Mauro Serrano', 'Política de privacidad + registro de tratamiento de datos', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D7-06', 'D7 — Tecnología, datos y ciberseguridad', 'FSCA', 'POPIA S.55', 'Nombrar Information Officer (POPIA - Sudáfrica)', 'Por evento', 'Por evento', 'Mauro Serrano', 'Designación registrada ante Information Regulator', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D7-07', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'POPIA / DPA Mauritius', 'Reportar brechas de datos personales al regulador competente', 'Por evento', 'Por evento', 'Mauro Serrano', 'Notificación de brecha enviada', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),
('D7-08', 'D7 — Tecnología, datos y ciberseguridad', 'Ambas', 'FAIS / FSC / ISO 27001 A.12', 'Mantener logs de auditoría de sistemas', 'Continua', 'Continua', 'Mauro Serrano', 'Logs de auditoría disponibles y protegidos', NULL, 'Compliant', 1, 'Initial state — pending first assessment', ''),

-- D8: Vigilancia y gestión de cambios normativos
('D8-01', 'D8 — Vigilancia y gestión de cambios normativos', 'FSCA', 'Interno', 'Monitorear publicaciones FSCA: Notices, Conduct Standards, Board Notices', 'Semanal', 'Semanal', 'Mauro Serrano', 'Clasificación de impacto + resumen ejecutivo', CURRENT_DATE + INTERVAL '7 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D8-02', 'D8 — Vigilancia y gestión de cambios normativos', 'FSC Mauritius', 'Interno', 'Monitorear publicaciones FSC Mauritius: Communiqués, Circulars, FSC Rules', 'Semanal', 'Semanal', 'Mauro Serrano', 'Clasificación de impacto + resumen ejecutivo', CURRENT_DATE + INTERVAL '7 days', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D8-03', 'D8 — Vigilancia y gestión de cambios normativos', 'FSC Mauritius', 'Interno', 'Monitorear cambios en FIAMLA y FIAML Regulations', 'Mensual', 'Mensual', 'Mauro Serrano', 'Actualizar programa AML/CFT si aplica', CURRENT_DATE + INTERVAL '1 month', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D8-04', 'D8 — Vigilancia y gestión de cambios normativos', 'FSCA', 'Interno', 'Monitorear cambios en FICA (Sudáfrica) y FIC Guidelines', 'Mensual', 'Mensual', 'Mauro Serrano', 'Actualizar programa AML/CFT si aplica', CURRENT_DATE + INTERVAL '1 month', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D8-05', 'D8 — Vigilancia y gestión de cambios normativos', 'Ambas', 'Interno', 'Monitorear FATF / OECD (estándares internacionales AML)', 'Trimestral', 'Trimestral', 'Mauro Serrano', 'Evaluar impacto en políticas AML', CURRENT_DATE + INTERVAL '3 months', 'En progreso', 1, 'Initial state — pending first assessment', ''),
('D8-06', 'D8 — Vigilancia y gestión de cambios normativos', 'Ambas', 'Interno', 'Registrar en historial todos los cambios normativos detectados', 'Por evento', 'Por evento', 'Mauro Serrano', 'Entrada en historial de cambios normativos', NULL, 'Compliant', 1, 'Initial state — pending first assessment', '');
